In [13]:
import pandas as pd
import h5py
import numpy as np

In [2]:
feature_data = h5py.File('../../datasets/MCA_BatchRemoved_Merge_dge.h5ad','r')

In [4]:
feature_data.keys()

<KeysViewHDF5 ['X', 'obs', 'var']>

In [6]:
feature_data['X'].shape

(333778, 34947)

In [7]:
main_df = pd.DataFrame()

In [9]:
main_df

Empty DataFrame
Columns: []
Index: []

In [18]:
feature_data['X'][0:10]

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 3., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.],
       [2., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [15]:
feature_data['obs'][:10]

array([(b'AdultBladder_1.CCATCTAGCGAGTTTAGG',),
       (b'AdultBladder_1.GAGGAGCGCTTGATACAG',),
       (b'AdultBladder_1.CCAGACACAATAGAATTA',),
       (b'AdultBladder_1.CCGACGGGACATATGGCG',),
       (b'AdultBladder_1.TAGCATTCAAAGATTCCA',),
       (b'AdultBladder_1.CTCCATCCATCTTTTAGG',),
       (b'AdultBladder_1.CAAAGTAGGACTAAGTAC',),
       (b'AdultBladder_1.TAGCATTGCGGAAACCTA',),
       (b'AdultBladder_1.ACACCCACGTTGCACAAG',),
       (b'AdultBladder_1.CGCACCATCTCTTAGTCG',)], dtype=[('index', 'S49')])

In [16]:
feature_data['var'][:10]

array([(b'0610007P14Rik',), (b'0610009B22Rik',), (b'0610009E02Rik',),
       (b'0610009L18Rik',), (b'0610009O20Rik',), (b'0610010F05Rik',),
       (b'0610012G03Rik',), (b'0610030E20Rik',), (b'0610033M10Rik',),
       (b'0610037L13Rik',)], dtype=[('index', 'S15')])

In [19]:
feature_data['X'][0][0].dtype

dtype('float32')

In [23]:
feature_data['X'].shape

(333778, 34947)

In [20]:
def preprocess_data(input_digi):
    if input_digi>=1:
        return 1.0
    return 0.0

In [24]:
X = feature_data['X']

In [25]:
X[...]

MemoryError: Unable to allocate 43.5 GiB for an array with shape (333778, 34947) and data type float32

In [49]:
processed_data.close()
processed_data = h5py.File('../../datasets/processed_dataset_1.h5ad','w')

In [50]:
# copy dataset into the new dataset
feature_data.copy('X', processed_data)
feature_data.copy('var', processed_data)
feature_data.copy('obs', processed_data)

In [51]:
processed_data.keys()

<KeysViewHDF5 ['X', 'obs', 'var']>

In [54]:
processed_data['X'].shape

(333778, 34947)

In [55]:
processed_data['X'][:10]

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 3., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.],
       [2., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [56]:
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        tmp_digi = X[i][j]
        if tmp_digi >= 1.0:
            tmp_digi = 1.0
        else:
            tmp_digi = 0.0
        processed_data['X'][i][j] = tmp_digi

KeyboardInterrupt: 

In [ ]:
processed_data['X'][:10]

In [1]:
import h5py
from sklearn.model_selection import train_test_split

In [2]:
data_f = h5py.File('../../datasets/process_dataset.h5ad', 'r')

In [3]:
train_test_f.close()

NameError: name 'train_test_f' is not defined

In [4]:
train_test_f = h5py.File('../../datasets/train_test_dataset.h5ad', 'w')

In [5]:
train_test_f.keys()

<KeysViewHDF5 []>

In [6]:
19634

19634

In [7]:
train_test_f.create_dataset('train_X', dtype='f')
train_test_f.create_dataset('train_y', dtype='f')
train_test_f.create_dataset('test_X', dtype='f')
train_test_f.create_dataset('test_y', dtype='f')

<HDF5 dataset "test_y": shape None, type "<f4">

In [32]:
train_test_f.keys()
train_test_f.close()

In [9]:
data_f.keys()

<KeysViewHDF5 ['X', 'labels', 'obs', 'var']>

In [10]:
data_f['labels'][...]

array([83, 83, 83, ..., 45, 40, 15])

In [11]:
import numpy as np

In [15]:
import pandas as pd

In [42]:
train_test_f.close()

In [43]:
i=0
while i < data_f['X'].shape[0]:
    tmp_X = data_f['X'][i:i+19634]
    tmp_y = data_f['labels'][i:i+19634]
    train_X, test_X, train_y, test_y = train_test_split(tmp_X, tmp_y, test_size=0.2, random_state=42)
    
    if i==0:
        with h5py.File('../../datasets/train_test_dataset.h5ad', 'w') as hf:
            hf.create_dataset(name='train_X', data=train_X, dtype=np.float, chunks=(1024, train_X.shape[1]))
            hf.create_dataset(name='train_y', data=train_y, dtype=np.int, chunks=(1024,))
            hf.create_dataset(name='test_X', data=test_X, dtype=np.float, chunks=(1024, test_X.shape[1]))
            hf.create_dataset(name='test_y', data=test_y, dtype=np.int, chunks=(1024,))
    else:
        with h5py.File('../../datasets/train_test_dataset.h5ad', 'a') as hf:
            hf["train_X"].resize((hf["train_X"].shape[0] + train_X.shape[0]), axis = 0)
            hf["train_X"][hf["train_X"].shape[0]:] = train_X

            hf["test_X"].resize((hf["test_X"].shape[0] + test_X.shape[0]), axis = 0)
            hf["test_X"][hf["test_X"].shape[0]:] = test_X

            hf["train_y"].resize((hf["train_y"].shape[0] + train_y.shape[0]), axis = 0)
            hf["train_y"][hf["train_y"].shape[0]:] = train_y

            hf["test_y"].resize((hf["test_y"].shape[0] + test_y.shape[0]), axis = 0)
            hf["test_y"][hf["test_y"].shape[0]:] = test_y

    i+=19634
    process_percent = (i+1)/data_f['X'].shape[0]
    percentage = "{:.1%}".format(process_percent)
    print(percentage)

5.9%
11.8%
17.6%
23.5%
29.4%
35.3%
41.2%
47.1%
52.9%
58.8%
64.7%
70.6%
76.5%
82.4%
88.2%
94.1%
100.0%


In [44]:
train_test_f = h5py.File('../../datasets/train_test_dataset.h5ad', 'r')

In [45]:
train_test_f.keys()

<KeysViewHDF5 ['test_X', 'test_y', 'train_X', 'train_y']>

In [46]:
data_f['X'].shape

(333778, 34947)

In [47]:
data_f['X'][:5]

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [48]:
data_f['labels'][:5]

array([83, 83, 83, 83, 83])

In [49]:
train_test_f['test_X'].shape

(3927, 34947)

In [50]:
train_test_f['train_X'].shape

(15707, 34947)

In [49]:
import pandas as pd

In [55]:
pd_hf = pd.read_hdf('../../datasets/process_dataset.h5ad', mode = 'r')

ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.

In [11]:
import h5py
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
data_f = h5py.File('../../datasets/process_dataset.h5ad', 'r')

In [3]:
data_f['X'].shape

(333778, 34947)

In [4]:
data_f['X'].shape[0]/2

166889.0

In [5]:
data_f['X'].shape[0]/17

19634.0

In [26]:
tmp_X = data_f['X'][:19634]
tmp_y = data_f['labels'][:19634]

In [27]:
train_X, test_X, train_y, test_y = train_test_split(tmp_X, tmp_y, test_size=0.2, random_state=42)

In [25]:
train_test_dataset.close()

In [31]:
train_X.shape

(15707, 34947)

In [33]:
train_y.shape[1]

IndexError: tuple index out of range

In [28]:
train_test_dataset = h5py.File('../../datasets/train_test_dataset.h5ad', 'w')

In [34]:
train_test_dataset.create_dataset(name='train_X', data=train_X, dtype=np.float, chunks=(1024, train_X.shape[1]))
train_test_dataset.create_dataset(name='train_y', data=train_y, dtype=np.int, chunks=(1024,))
train_test_dataset.create_dataset(name='test_X', data=test_X, dtype=np.float, chunks=(1024, test_X.shape[1]))
train_test_dataset.create_dataset(name='test_y', data=test_y, dtype=np.int, chunks=(1024,))

<HDF5 dataset "test_y": shape (3927,), type "<i8">

In [35]:
train_test_dataset['train_X'].shape

(15707, 34947)

In [21]:
tmp_X = data_f['X'][19634:2*19634]
tmp_y = data_f['labels'][19634:2*19634]

In [22]:
train_X, test_X, train_y, test_y = train_test_split(tmp_X, tmp_y, test_size=0.2, random_state=42)

In [23]:
train_test_dataset['train_X'][19634:] = train_X

In [24]:
train_test_dataset['train_X'].shape

(15707, 34947)