In [1]:
import pandas as pd
import numpy as np

In [2]:
 # processed_dge folder contains all new defined datasets
 # get all shapes from processed_dge files
 shape_list = []
 for root, dirs, files in os.walk("/home/jay/Documents/projects/todo_files/ml_final_pro/datasets/processed_dge", topdown=False):
     for name in files:
        file_dir = os.path.join(root, name)
        tmp_df = pd.read_csv(file_dir)
        shape_list.append(tmp_df.shape)


In [3]:
tmp_df = pd.read_csv('/home/jay/Documents/projects/todo_files/ml_final_pro/datasets/processed_dge/Bladder_1.csv')

In [19]:
tmp_df

Unnamed: 0  0610007P14Rik  0610009B22Rik  \
0     Bladder_1.CCATCTAGCGAGTTTAGG              1              0   
1     Bladder_1.GAGGAGCGCTTGATACAG              1              3   
2     Bladder_1.CCAGACACAATAGAATTA              1              0   
3     Bladder_1.CCGACGGGACATATGGCG              1              0   
4     Bladder_1.TAGCATTCAAAGATTCCA              1              3   
...                            ...            ...            ...   
2741  Bladder_1.AAAACGCAACAAGGGCGA              0              0   
2742  Bladder_1.TTAACTGAGGAGGGGCGA              0              0   
2743  Bladder_1.GAGTCGGTCGGTATCAAC              0              0   
2744  Bladder_1.CCAGACCATGATAAGTAC              0              0   
2745  Bladder_1.CAACAAAGATGGTTTAGG              0              0   

      0610009E02Rik  0610009L18Rik  0610009O20Rik  0610010F05Rik  \
0                 0              0              0              0   
1                 0              0              0              0   
2                 1              0              0              0   
3                 0              0              1              0   
4                 0              1              0              0   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610010K14Rik  0610012G03Rik  0610025J13Rik  ...  n-R5s195  n-R5s21  \
0                 0              2              0  ...         0        0   
1                 0              2              0  ...         0        0   
2                 0              5              0  ...         0        0   
3                 0              1              0  ...         0        0   
4                 0              7              0  ...         0        0   
...             ...            ...            ...  ...       ...      ...   
2741              0              0              0  ...         0        0   
2742              0              0              0  ...         0        0   
2743              0              0              0  ...         0        0   
2744              0              0              0  ...         0        0   
2745              0              0              0  ...         0        0   

      n-R5s25  n-R5s28  n-R5s33  n-R5s77  n-R5s96  n-TStga1  target_id  \
0           0        0        0        0        0         0          9   
1           0        0        0        0        0         0          9   
2           0        0        0        0        0         0          9   
3           0        0        0        0        0         0          9   
4           0        0        0        0        0         0          9   
...       ...      ...      ...      ...      ...       ...        ...   
2741        0        0        0        0        0         0          4   
2742        0        0        0        0        0         0          4   
2743        0        0        0        0        0         0          6   
2744        0        0        0        0        0         0          4   
2745        0        0        0        0        0         0          4   

                      annotation  
0                  Umbrella cell  
1                  Umbrella cell  
2                  Umbrella cell  
3                  Umbrella cell  
4                  Umbrella cell  
...                          ...  
2741                  Urothelium  
2742                  Urothelium  
2743  Epithelial cell_Upk3a high  
2744                  Urothelium  
2745                  Urothelium  

[2746 rows x 20673 columns]

In [3]:
shape_list

[(5298, 18700),
 (4347, 19957),
 (1931, 17970),
 (352, 15164),
 (2035, 19702),
 (829, 17634),
 (3617, 20271),
 (1575, 17939),
 (13019, 20602),
 (135, 14964),
 (2771, 19822),
 (1963, 19320),
 (3624, 16228),
 (2473, 19524),
 (2746, 20673),
 (261, 16708),
 (4289, 17641),
 (4571, 19555),
 (753, 18723),
 (2699, 16491),
 (2216, 24182),
 (7365, 20193),
 (6453, 19202),
 (7319, 17846),
 (3610, 20286),
 (6192, 19723),
 (2512, 20768),
 (6076, 20118),
 (19489, 21080),
 (2389, 18881),
 (4369, 19539),
 (3014, 19796),
 (5808, 19700),
 (1592, 21366),
 (1474, 15499),
 (2432, 20116),
 (3201, 16711),
 (658, 14718),
 (3438, 20087),
 (3082, 20921),
 (1671, 18585),
 (1970, 17548),
 (9991, 20685),
 (3392, 20219),
 (510, 15535),
 (2466, 16403),
 (3472, 19738),
 (1102, 17291),
 (3948, 19496),
 (1873, 19432),
 (11789, 25786),
 (1217, 18567),
 (8166, 16823),
 (1704, 18857),
 (3285, 20168),
 (4424, 19597),
 (283, 14302),
 (4044, 21062),
 (1414, 19590),
 (1031, 15580)]

In [5]:
# convert to np array
shape_list = np.array(shape_list)

In [6]:
shape_list.shape

(60, 2)

In [7]:
shape_list

array([[ 5298, 18700],
       [ 4347, 19957],
       [ 1931, 17970],
       [  352, 15164],
       [ 2035, 19702],
       [  829, 17634],
       [ 3617, 20271],
       [ 1575, 17939],
       [13019, 20602],
       [  135, 14964],
       [ 2771, 19822],
       [ 1963, 19320],
       [ 3624, 16228],
       [ 2473, 19524],
       [ 2746, 20673],
       [  261, 16708],
       [ 4289, 17641],
       [ 4571, 19555],
       [  753, 18723],
       [ 2699, 16491],
       [ 2216, 24182],
       [ 7365, 20193],
       [ 6453, 19202],
       [ 7319, 17846],
       [ 3610, 20286],
       [ 6192, 19723],
       [ 2512, 20768],
       [ 6076, 20118],
       [19489, 21080],
       [ 2389, 18881],
       [ 4369, 19539],
       [ 3014, 19796],
       [ 5808, 19700],
       [ 1592, 21366],
       [ 1474, 15499],
       [ 2432, 20116],
       [ 3201, 16711],
       [  658, 14718],
       [ 3438, 20087],
       [ 3082, 20921],
       [ 1671, 18585],
       [ 1970, 17548],
       [ 9991, 20685],
       [ 33

In [8]:
smallest_num = np.amin(shape_list, axis=0)
largest_num = np.amax(shape_list, axis=0)

In [9]:
smallest_num

array([  135, 14302])

In [10]:
largest_num

array([19489, 25786])

In [11]:
total_num_ob = np.sum(shape_list, axis=0)

In [12]:
total_num_ob

array([ 219729, 1133584])

In [14]:
import h5py

In [16]:
f = h5py.File('/home/jay/Downloads/ACTINN-master/test_data/train_set.h5', 'r')

In [17]:
f.keys()

<KeysViewHDF5 ['dge']>

In [20]:
f['dge']

<HDF5 group "/dge" (4 members)>

In [22]:
f['dge'].keys()

<KeysViewHDF5 ['axis0', 'axis1', 'block0_items', 'block0_values']>

In [29]:
f['dge']['axis0'][:10]

array([b'tma_mfd_1808', b'tma_mfd_32608', b'tma_mfd_2589',
       b'tma_mfd_13999', b'tma_mfd_2621', b'tma_mfd_5055', b'tma_mfd_796',
       b'tma_mfd_26185', b'tma_mfd_30053', b'tma_mfd_8084'], dtype='|S13')

In [28]:
f['dge']['axis1'][:10]

array([b'0610005C13Rik', b'0610007C21Rik', b'0610007L01Rik',
       b'0610007N19Rik', b'0610007P08Rik', b'0610007P14Rik',
       b'0610007P22Rik', b'0610009B22Rik', b'0610009D07Rik',
       b'0610009L18Rik'], dtype='|S14')

In [27]:
f['dge']['block0_items'][:10]

array([b'tma_mfd_1808', b'tma_mfd_32608', b'tma_mfd_2589',
       b'tma_mfd_13999', b'tma_mfd_2621', b'tma_mfd_5055', b'tma_mfd_796',
       b'tma_mfd_26185', b'tma_mfd_30053', b'tma_mfd_8084'], dtype='|S13')

In [30]:
f['dge']['block0_values'][:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [2., 1., 0., ..., 0., 5., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
tmp_df = pd.read_csv('/home/jay/Documents/projects/todo_files/ml_final_pro/datasets/processed_dge/Bladder_1.csv')

In [46]:
tmp_df

Unnamed: 0  0610007P14Rik  0610009B22Rik  \
0     Bladder_1.CCATCTAGCGAGTTTAGG              1              0   
1     Bladder_1.GAGGAGCGCTTGATACAG              1              3   
2     Bladder_1.CCAGACACAATAGAATTA              1              0   
3     Bladder_1.CCGACGGGACATATGGCG              1              0   
4     Bladder_1.TAGCATTCAAAGATTCCA              1              3   
...                            ...            ...            ...   
2741  Bladder_1.AAAACGCAACAAGGGCGA              0              0   
2742  Bladder_1.TTAACTGAGGAGGGGCGA              0              0   
2743  Bladder_1.GAGTCGGTCGGTATCAAC              0              0   
2744  Bladder_1.CCAGACCATGATAAGTAC              0              0   
2745  Bladder_1.CAACAAAGATGGTTTAGG              0              0   

      0610009E02Rik  0610009L18Rik  0610009O20Rik  0610010F05Rik  \
0                 0              0              0              0   
1                 0              0              0              0   
2                 1              0              0              0   
3                 0              0              1              0   
4                 0              1              0              0   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610010K14Rik  0610012G03Rik  0610025J13Rik  ...  n-R5s195  n-R5s21  \
0                 0              2              0  ...         0        0   
1                 0              2              0  ...         0        0   
2                 0              5              0  ...         0        0   
3                 0              1              0  ...         0        0   
4                 0              7              0  ...         0        0   
...             ...            ...            ...  ...       ...      ...   
2741              0              0              0  ...         0        0   
2742              0              0              0  ...         0        0   
2743              0              0              0  ...         0        0   
2744              0              0              0  ...         0        0   
2745              0              0              0  ...         0        0   

      n-R5s25  n-R5s28  n-R5s33  n-R5s77  n-R5s96  n-TStga1  target_id  \
0           0        0        0        0        0         0          9   
1           0        0        0        0        0         0          9   
2           0        0        0        0        0         0          9   
3           0        0        0        0        0         0          9   
4           0        0        0        0        0         0          9   
...       ...      ...      ...      ...      ...       ...        ...   
2741        0        0        0        0        0         0          4   
2742        0        0        0        0        0         0          4   
2743        0        0        0        0        0         0          6   
2744        0        0        0        0        0         0          4   
2745        0        0        0        0        0         0          4   

                      annotation  
0                  Umbrella cell  
1                  Umbrella cell  
2                  Umbrella cell  
3                  Umbrella cell  
4                  Umbrella cell  
...                          ...  
2741                  Urothelium  
2742                  Urothelium  
2743  Epithelial cell_Upk3a high  
2744                  Urothelium  
2745                  Urothelium  

[2746 rows x 20673 columns]

In [47]:
# exclude the target_id and target annotation
tmp_df.iloc[:,1:-2]

0610007P14Rik  0610009B22Rik  0610009E02Rik  0610009L18Rik  \
0                 1              0              0              0   
1                 1              3              0              0   
2                 1              0              1              0   
3                 1              0              0              0   
4                 1              3              0              1   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610009O20Rik  0610010F05Rik  0610010K14Rik  0610012G03Rik  \
0                 0              0              0              2   
1                 0              0              0              2   
2                 0              0              0              5   
3                 1              0              0              1   
4                 0              0              0              7   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610025J13Rik  0610030E20Rik  ...  n-R5s102  n-R5s151  n-R5s195  \
0                 0              1  ...         0         0         0   
1                 0              1  ...         0         0         0   
2                 0              0  ...         0         0         0   
3                 0              0  ...         0         0         0   
4                 0              1  ...         0         0         0   
...             ...            ...  ...       ...       ...       ...   
2741              0              0  ...         0         0         0   
2742              0              1  ...         0         0         0   
2743              0              0  ...         0         0         0   
2744              0              0  ...         0         0         0   
2745              0              0  ...         0         0         0   

      n-R5s21  n-R5s25  n-R5s28  n-R5s33  n-R5s77  n-R5s96  n-TStga1  
0           0        0        0        0        0        0         0  
1           0        0        0        0        0        0         0  
2           0        0        0        0        0        0         0  
3           0        0        0        0        0        0         0  
4           0        0        0        0        0        0         0  
...       ...      ...      ...      ...      ...      ...       ...  
2741        0        0        0        0        0        0         0  
2742        0        0        0        0        0        0         0  
2743        0        0        0        0        0        0         0  
2744        0        0        0        0        0        0         0  
2745        0        0        0        0        0        0         0  

[2746 rows x 20670 columns]

In [48]:
tmp_df.iloc[:,1:-2] = tmp_df.iloc[:,1:-2].mask(tmp_df.iloc[:,1:-2] > 1, 1)

In [49]:
tmp_df.iloc[:,1:-2]

0610007P14Rik  0610009B22Rik  0610009E02Rik  0610009L18Rik  \
0                 1              0              0              0   
1                 1              1              0              0   
2                 1              0              1              0   
3                 1              0              0              0   
4                 1              1              0              1   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610009O20Rik  0610010F05Rik  0610010K14Rik  0610012G03Rik  \
0                 0              0              0              1   
1                 0              0              0              1   
2                 0              0              0              1   
3                 1              0              0              1   
4                 0              0              0              1   
...             ...            ...            ...            ...   
2741              0              0              0              0   
2742              0              0              0              0   
2743              0              0              0              0   
2744              0              0              0              0   
2745              0              0              0              0   

      0610025J13Rik  0610030E20Rik  ...  n-R5s102  n-R5s151  n-R5s195  \
0                 0              1  ...         0         0         0   
1                 0              1  ...         0         0         0   
2                 0              0  ...         0         0         0   
3                 0              0  ...         0         0         0   
4                 0              1  ...         0         0         0   
...             ...            ...  ...       ...       ...       ...   
2741              0              0  ...         0         0         0   
2742              0              1  ...         0         0         0   
2743              0              0  ...         0         0         0   
2744              0              0  ...         0         0         0   
2745              0              0  ...         0         0         0   

      n-R5s21  n-R5s25  n-R5s28  n-R5s33  n-R5s77  n-R5s96  n-TStga1  
0           0        0        0        0        0        0         0  
1           0        0        0        0        0        0         0  
2           0        0        0        0        0        0         0  
3           0        0        0        0        0        0         0  
4           0        0        0        0        0        0         0  
...       ...      ...      ...      ...      ...      ...       ...  
2741        0        0        0        0        0        0         0  
2742        0        0        0        0        0        0         0  
2743        0        0        0        0        0        0         0  
2744        0        0        0        0        0        0         0  
2745        0        0        0        0        0        0         0  

[2746 rows x 20670 columns]

In [57]:
np.where(tmp_df.iloc[:,1:-2] > 1.0)

(array([], dtype=int64), array([], dtype=int64))

In [3]:
new_pre_process_dir = '../../datasets/pre_processed_datasets'

In [2]:
import os

In [4]:
if not os.path.exists(new_pre_process_dir):
    os.mkdir(new_pre_process_dir)

In [2]:
new_file_dir = os.path.join(new_pre_process_dir, 'Bladder_1.csv')

NameError: name 'new_pre_process_dir' is not defined

In [ ]:
new_file_dir

In [ ]:
tmp_df.to_csv(new_file_dir)

In [5]:
# preprocess the dataset to binary for sequence in gene
for root, dirs, files in os.walk("/home/jay/Documents/projects/todo_files/ml_final_pro/datasets/processed_dge", topdown=False):
     for name in files:
        file_dir = os.path.join(root, name)
        tmp_df = pd.read_csv(file_dir)
        tmp_df.iloc[:,1:-2] = tmp_df.iloc[:,1:-2].mask(tmp_df.iloc[:,1:-2] > 1, 1)
        new_file_dir = os.path.join(new_pre_process_dir, name)
        tmp_df.to_csv(new_file_dir)

In [ ]:
tmp_df

In [2]:
df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})

df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})

In [7]:
df1

a  b
0  foo  1
1  bar  2

In [8]:
df2

a  c
0  foo  3
1  baz  4

In [5]:
df1.merge(df2, how='inner', on='a')

a  b  c
0  foo  1  3

In [6]:
df1.merge(df2, how='left', on='a')

a  b    c
0  foo  1  3.0
1  bar  2  NaN

In [9]:
df1.merge(df2, how='outer', on='a')

a    b    c
0  foo  1.0  3.0
1  bar  2.0  NaN
2  baz  NaN  4.0

In [4]:
tmp_df.shape

(2746, 20673)

In [7]:
int(3/2)

1

In [5]:
step = int(tmp_df.shape[0]/2)

In [6]:
step

1373

In [8]:
for i in range(2):
    print(i)

0
1
